#######################################################
#security.basic.enabled=false
#######################################################       
# EMBEDDED SERVER CONFIGURATION (ServerProperties)
#######################################################
server:
    port: 8081
    session-timeout: 600
    
    
######################################################    
# DATABASE CONFIGURATIONS
#######################################################    



